### PR TITLE
Update To Allow Twig 2.x

### PR DESCRIPTION
**Pull request by quantumpacket**
Just adds support for Twig 2.x in addition to keeping current support for 1.x.

### CODE REVIEW

**Comment by enygma** [comment]
Nice - thanks for the update! Do you know offhand if there's any deprecated handling in 2.x that would cause the current code here to break? I haven't looked at the difference...

**Comment by quantumpacket** [comment]
**Deprecations:** http://twig.sensiolabs.org/doc/1.x/deprecated.html

Expose's only Twig code is here [./src/Expose/Notify/Email.php#L100-L102](https://github.com/enygma/expose/blob/9be969b088c1d05ef20208fc591bf38e407b9746/src/Expose/Notify/Email.php#L100-L102) and of course the template [./src/Expose/Template/Notify/Email.twig](https://github.com/enygma/expose/blob/master/src/Expose/Template/Notify/Email.twig)

The template has no breaking code. The only Twig calls made is for `Twig_Loader_Filesystem()` and `Twig_Environment()` and `loadTemplate()` none of which appear to be deprecated. I'd have another set of eyes verify though :)

**Comment by enygma** [comment]
Confirmed - looks good to me, merging.

**Comment by quantumpacket** [comment]
@enygma could we have a new release pushed out? Haven't had one since 2015 and there's been quite a few changes. Thanks!

**Comment by enygma** [comment]
@quantumpacket done! Welcome to 3.0 :)

**Pull request merged**
